### ISSUE TITLE
Spelling of Yeoman

### ISSUE THREAD

**Issue by foffenburger** [pagalvin/office365BootcampOct2017#1]
Inconsistent spelling of yeoman as yoeman on various slides.  Attached updated file with corrections since I'm a git noob.
[Introducing SharePoint Framework v1_1.pptx](https://github.com/pagalvin/office365BootcampOct2017/files/1443375/Introducing.SharePoint.Framework.v1_1.pptx)

**Comment by pagalvin** [comment]
Thanks!
 
I replaced my copy with the updated copy you provided.
